name: "Country"
version: "1.0"
website: 'https://sirblob.bosstop.ml'
main: tech.bosstop.country.Country
api-version: 1.19
authors: [Sir_Blob_]
load: STARTUP

commands:
  country:
    description: Country command
    usage: "/country <subcommand>"
    aliases: [ct]