name: "Towny"
version: "1.0"
website: 'https://sirblob.bosstop.ml'
main: ml.bosstop.towny.Towny
api-version: 1.19
authors: [Sir_Blob_]
load: STARTUP

commands:
  towny:
    description: Towny command
    usage: "/ty <subcommand>"
    aliases: [ty]
permissions:
  towny.chat:
    default: true
  towny.basic:
    default: true